### ISSUE TITLE
DNSMasq service start/restart policy

### ISSUE THREAD

**Issue by Miesvanderlippe** [bodsch/ansible-dnsmasq#4]
I’m running this playbook to service DNS on a VPN server. I’m binding DNSMasq to the VPN interface. This works as expected until I reboot the server. The interface for the VPN is not always up before the DNS service is started. 

The easiest thing I could come up with is to just set the restart policy to always restart. Another solution would be to allow us to set the dependencies for the service file (after: wg-quick@whatever). 

This would require a custom service file I imagine. 

What’s your opinion on this? Should I just edit the service file on disk and be done with it? Or is this something you would consider adding to the role?

**Comment by bodsch** [comment]
Dear @Miesvanderlippe!

I have a similar problem with openVPN and SSH ...

In general, this should be integrated into the role, as manual changes should be unnecessary due to automation.

I will probably create a custom service file here and publish it as a new release.

**Comment by bodsch** [comment]
Hi  @Miesvanderlippe 

Please try the [latest](https://github.com/bodsch/ansible-dnsmasq/releases/tag/1.1.0) release!
